language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

env:		
  global:		
    - PHPBB_BRANCH="master"		
    - PHPBB_VERSION="3.3"		
    - PHPBB_LANGUAGE="fr"

sudo: false

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi;
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then php --version; fi;
  - composer self-update
  - composer --version

install:
  - mkdir -p $PHPBB_VERSION/$PHPBB_LANGUAGE		
  - mkdir -p $PHPBB_VERSION/en/language		
  - mkdir -p $PHPBB_VERSION/en/styles/prosilver/theme
  - mv language $PHPBB_VERSION/$PHPBB_LANGUAGE
  - mv styles $PHPBB_VERSION/$PHPBB_LANGUAGE
  - git clone "https://github.com/phpbb/phpbb.git" --branch=$PHPBB_BRANCH
  - mv phpbb/phpBB/language/en $PHPBB_VERSION/en/language		
  - mv phpbb/phpBB/styles/prosilver/theme/en $PHPBB_VERSION/en/styles/prosilver/theme
  - composer install --no-interaction --prefer-source

script:
  - php vendor/bin/PhpbbTranslationValidator.php validate --phpbb-version=$PHPBB_VERSION $PHPBB_LANGUAGE --display-notices

notifications:
  email:
    on_failure: change
