name: Validation
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4' ]
    env:
      PHPBB_BRANCH: 3.3.x
      PHPBB_VERSION: 3.3
      PHPBB_LANGUAGE: fr
    name: Build with PHP ${{ matrix.php }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Validate Composer
        run: composer validate
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Create directories
        run: |
          mkdir -p $PHPBB_VERSION/$PHPBB_LANGUAGE
          mkdir -p $PHPBB_VERSION/en/language
          mkdir -p $PHPBB_VERSION/en/styles/prosilver/theme
      - name: Download phpBB
        run: git clone "https://github.com/phpbb/phpbb.git" --branch=$PHPBB_BRANCH
      - name: Move files and directories
        run: |
          mv language $PHPBB_VERSION/$PHPBB_LANGUAGE
          mv styles $PHPBB_VERSION/$PHPBB_LANGUAGE
          mv phpbb/phpBB/language/en $PHPBB_VERSION/en/language
          mv phpbb/phpBB/styles/prosilver/theme/en $PHPBB_VERSION/en/styles/prosilver/theme
      - name: Install the translation validator
        run: composer install --prefer-dist --no-interaction --no-progress
      - name: Display the version of the translation validator
        run: php vendor/bin/translation.php --version
      - name: Run the translation validator
        run: php vendor/bin/translation.php validate $PHPBB_LANGUAGE --phpbb-version=$PHPBB_VERSION --display-notices
